# A Quick Guide to the Julia Language

For use with optimization problems. Internal links in Menu only works when file opened in Jupyter Notebook.

### Menu

###### [1.Printing](#1.printing)
###### [2.Logical Operators](#2.logicaloperators)
###### [3.Functions](#3.functions)
###### [4.Control Flow](#4.controlflow)
###### [5.Vectors, Matrices and Related Manipulations](#5)

### Printing

In [56]:
# single quotes cannot be used within println()
println("Hello, World!") 

Hello, World!


In [57]:
# Julia's precision
println(5-3.8) 

1.2000000000000002


In [126]:
# concatenating strings and printing multiple times
println(("Hello," * " my world! ")^2) 

Hello, my world! Hello, my world! 


<a id='2.logicaloperators'></a>

### Logical Operators:

`&&` is AND,
    <br>`&` is the bitwise AND,
    <br>`||` is OR,
    <br>`|` is the bitwise OR,
    <br>`!` is NOT,
    <br>and then there is `true` and `false`.

In [59]:
# Julia evaluates from left to right
false && true || true 

true

<a id='3.functions'></a>

### Functions

In [34]:
# type declaration of function outputs
function plusfive(x)::Int8 
        x + 5
end

typeof(plusfive(3))

Int8

In [35]:
# operators are functions as well
f = + 
f(1, 2, 3)

6

In [46]:
# a function with multiple points of return
function g(x, y)::Float16
    x = abs(x)
    y = abs(y)
    
    if x > y
        return x
    end
    
    if y > x
        return y
    end
    
    return 0
end

println(g(2, 1), ", ", g(2, 3), ", ", g(1, 1))

2.0, 3.0, 0.0


In [47]:
# anonymous functions, akin to lambda functions in Python
function (x)
    x^2 + 1
end
# or 
x -> x^2 + 1

# to be used in situations like
map(x -> x^2 + 1, [5, 6, 7])

3-element Array{Int64,1}:
 26
 37
 50

In [53]:
# multiple values to be returned
function twovalues(x, y)
    x+y, x*y
end

# Julia supports unpacking
# notice that a function producing multiple outputs will produce them in a tuple when no unpacking is done
x, y = twovalues(3, 5)
println(x,',', y, ',', twovalues(3, 5))

8,15,(8, 15)


In [72]:
# optional arguments with default values and type declaration
function date(y::Int64, m::Int64=1, d::Int64=1)
    println(y, m, d)
end

date(2012, 2)

201221


In [80]:
# function chaining, also called 'piping'
# syntax: input |> function_1 |> function_2 |> ... |> function_n

1:10 |> sum |> sqrt

# the right-to-left syntax is omitted here for simplicity

7.416198487095663

In [82]:
# broadcasting, i.e. an ordered one-to-one value-function execution

["a", "list", "of", "strings"] .|> [uppercase, reverse, titlecase, length]

4-element Array{Any,1}:
  "A"   
  "tsil"
  "Of"  
 7      

In [97]:
# vectorized operations
g(x)= x^2+1

A = [1.0, 2.0, 3.0]

g.(A)

3-element Array{Float64,1}:
  2.0
  5.0
 10.0

<a id='4.controlflow'></a>

### Control Flow

In [103]:
# conditional evaluation syntax
x = 1
y = -10

if x < y
    println("x is less than y")
elseif x > y
    println("x is greater than y")
else
    println("x is equal to y")
end

# conditional evaluations in Julia are short-circuit

x is greater than y


In [107]:
# ternary operator `?:`
# left of `:` to be executed when true, and right to the executed when false; `?` to be put after the condition
x = 1; y = 2;

println(x < y ? "less than" : "not less than")

x = 1; y = 0;

println(x < y ? "less than" : "not less than")

less than
not less than


In [123]:
# WHILE loop syntax
i = 1

while i <= 2
    println(i)
    global i += 1
end

1
2


In [122]:
i = 1
while true
   println(i)
   if i >= 3
       break
   end
   global i += 1
end

1
2
3


In [120]:
# FOR loop syntax
for i = 1:3
    println(i)
end

1
2
3


In [121]:
for j = 1:1000
   println(j)
   if j >= 4
       break
   end
end

1
2
3
4


<a id='5'></a>

### Vectors, Matrices and Related Manipulations

In [127]:
# row vector
A = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [129]:
# column vector 
A = [1 2 3]'

3×1 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1
 2
 3

In [136]:
# 1D array
A = [1, 2, 3]


3-element Array{Int64,1}:
 1
 2
 3

In [137]:
# or
B = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

In [156]:
# integers fron a to b with step size s A = a:s:b, a and b inclusive
A = 2:2:12
for i in A
    println(i)
end

2
4
6
8
10
12


In [160]:
# linearly spaced vector of k points, a and b inclusive
A = range(1, 5, length = 5)
for i in A
    println(i)
end

1.0
2.0
3.0
4.0
5.0


In [161]:
# a 2X2 matrix
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [162]:
# zeros
A = zeros(2, 2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [163]:
# ones
A = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [171]:
# identity matrix; dimensions to be adopted from neighboring matrices
using LinearAlgebra, Statistics, Compat
A = I

UniformScaling{Bool}
true*I

In [173]:
# diagonal matrix
A = Diagonal([1, 2, 3])

3×3 Diagonal{Int64,Array{Int64,1}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [176]:
# uniform random numbers
A = rand(2, 4)

2×4 Array{Float64,2}:
 0.586961  0.545751  0.356393  0.249445 
 0.742649  0.684603  0.852823  0.0290302

In [177]:
# normal random numbers
A = randn(2, 4)

2×4 Array{Float64,2}:
 -0.443837  -0.0687515  1.05628   -1.34141
  1.15189   -0.582624   0.951342   1.31712

In [182]:
# transpose
A = [1 2; 3 4]
transpose(A)

2×2 Transpose{Int64,Array{Int64,2}}:
 1  3
 2  4

In [185]:
# concatenate along axis 0 in Python
A = [[1 2] [1 2]] 
# or
A = hcat([1 2], [1 2])

1×4 Array{Int64,2}:
 1  2  1  2

In [187]:
# concatenate along axis 1 in Python
A = [[1 2];[1 2]] 
# or
A = vcat([1 2], [1 2])

2×2 Array{Int64,2}:
 1  2
 1  2

In [188]:
# reshape to 3 rows and 4 columns
# notice that Julia runs along the vertical axis first, like Python
A = reshape(1:12, 3, 4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [190]:
# convert a matrix to vector; think m.flatten() in Python
A = [1 2; 3 4]
A[:]

4-element Array{Int64,1}:
 1
 3
 2
 4

In [193]:
# indexing: element-wise
A[1, 2]

2

In [195]:
# indexing: a row
A[1, :]

2-element Array{Int64,1}:
 1
 2

In [196]:
# indexing: a column
A[:,1]

2-element Array{Int64,1}:
 1
 3

In [197]:
# deleting a row: assign A to the following
A[[1], :]

1×2 Array{Int64,2}:
 1  2

In [199]:
# return diagonals of a matrix as an array
diag(A)

2-element Array{Int64,1}:
 1
 4

In [200]:
# get dimensions of a matrix
nrow, ncol = size(A)

(2, 2)

In [202]:
# dot product
A = [1 2; 3 4]
B = [2 2; 2 2]
dot(A, B)

20

In [203]:
# matrix multiplication
A * B

2×2 Array{Int64,2}:
  6   6
 14  14

In [204]:
# element-wise multiplication
A .* B

2×2 Array{Int64,2}:
 2  4
 6  8

In [205]:
# inverse a matrix
inv(A)

2×2 Array{Float64,2}:
 -2.0   1.0
  1.5  -0.5

In [206]:
# determinant
det(A)

-2.0